apiVersion: v1
kind: Service
metadata:
  name: go-node-kube
spec:
  ports:
  - name: goapp
    port: 80
    targetPort: {{ .Values.GoServer.Port }}
    protocol: TCP
  selector:
    name: goapp
  type: LoadBalancer
