apiVersion: v1
kind: Service
metadata:
  name: go-node-kube
spec:
  ports:
  - name: goapp
    port: 80
    targetPort: {{ .Values.GoServer.Port }}
    protocol: TCP
  selector:
    name: goapp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nodepod
spec:
  ports:
  - name: nodeapp
    port: 3000
    targetPort: {{ .Values.NodeServer.Port }}
    protocol: TCP
  selector:
    name: nodeapp
  type: LoadBalancer
